# Generated by Django 5.0.6 on 2024-05-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryBuilderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('year_founded', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_from', models.IntegerField(blank=True, null=True)),
                ('employee_to', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
